name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install node packages
        run: npm install

      - name: Run ESLint
        run: npm run lint-in-file

      - name: Run SASS lint
        if: always()
        run: npm run stylelint

      - name: Run unit test
        if: always()
        run: npm run test
        env:
          CI: true

      - name: Run UI test
        if: always()
        uses: cypress-io/github-action@v1
        run: npm run cypress
        with:
          start: npm start
          wait-on: http://localhost:3000
        env:
          CYPRESS_VALID_EMAIL: ${{ secrets.REACT_APP_VALID_EMAIL }}
          CYPRESS_VALID_PASSWORD: ${{ secrets.REACT_APP_VALID_PASSWORD }}

      - name: Run Danger
        if: always()
        run: npm run danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
