name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  build-and-test:
    env:
      REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
      REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
      REACT_APP_VALID_EMAIL: ${{ secrets.REACT_APP_VALID_EMAIL }}
      REACT_APP_VALID_PASSWORD: ${{ secrets.REACT_APP_VALID_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install node packages
        run: npm install

      - name: Run ESLint
        run: npm run lint-in-file

      - name: Run SASS lint
        if: always()
        run: npm run stylelint

      - name: Run unit test
        if: always()
        run: npm run test
        env:
          CI: true

      - name: Run UI test
        if: always()
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: http://localhost:3000
          env: CYPRESS_VALID_EMAIL=${{ secrets.REACT_APP_VALID_EMAIL }},CYPRESS_VALID_PASSWORD=${{ secrets.REACT_APP_VALID_PASSWORD }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run Danger
        if: always() && github.ref != 'refs/heads/development' && github.ref != 'refs/heads/master'
        run: npm run danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
