name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install node packages
        run: npm install

      - name: Run ESLint
        run: npm run lint-in-file

      - name: Run SASS lint
        if: always()
        run: npm run stylelint

      - name: Run test
        if: always()
        run: npm run test
        env:
          CI: true

      - name: Run Danger
        if: always() && github.ref != 'refs/heads/development' && github.ref != 'refs/heads/master'
        run: npm run danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
